### PR TITLE
Bump git2 to version 0.11

### PR DESCRIPTION
**Pull request by krallin**
No changes were required, tests still pass. Is there any further testing you'd like me to do?

### CODE REVIEW

**Comment by tarcieri** [comment]
The main thing that's important is to synchronize versions with `cargo-edit`, which is presently on `0.10.1`. Unfortunately `cargo-edit` is a dependency of `cargo-audit`, not this crate at the moment.

Perhaps I should add `cargo-edit` as an (optional) dependency to this crate (and perhaps move the associated functionality to it too) in order to make this clearer.

**Comment by krallin** [comment]
Ah I see #131 was opened to achieve that as well.

I’m guessing we’re waiting on cargo-edit to publish a new version now that
they’ve merged
https://github.com/killercup/cargo-edit/pull/369 then?

Thanks!

**Comment by tarcieri** [comment]
Yup

**Comment by tarcieri** [comment]
Dup of #131

**Pull request closed without merging**
