### PR TITLE
Try to auto-detect proxy setting

### LINKED ISSUE #94: Implement https proxy support
Rustsec does not appear to support configuring git2 to use an https proxy to access the git repo. I would imagine many environments wanting to use this crate would be required to do so via an https proxy.

In the meantime I can separately vendor the advisory-db repo, but it would be nice to be able to fetch it live as well.

### PR DESCRIPTION
**Pull request by tjodden**
Set `proxy_options` to `auto` when fetching the repository, which tells libgit2 to try to auto-detect proxy from the environment and git settings.

I've successfully tested this at work (where using a HTTPS proxy is required) with the environment variable `https_proxy` set appropriately. Looking at the libgit2 source it seems to check for `http_proxy`, `https_proxy`, `HTTP_PROXY` and `HTTPS_PROXY` env variables.

I've also tested this at home without any proxy and the `https_proxy` etc env variables unset.

Closes #94.

### CODE REVIEW

**Comment by tarcieri** [comment]
Ugh, fun:

```
- There was an unexpected error when executing this Action. For help debugging what went wrong, please contact support@github.com. The unique ID for this error is ea9f2d7a-f9bc-11e9-8f36-e3be7b13a6e8
``

**Comment by tjodden** [comment]
The two "1.35.0" failures seem unrelated to my change. Looks like toml 0.5.4 doesn't compile with rustc 1.35.0 because it uses the `iter_copied` feature. I guess the dependency needs to be changed to an earlier version of toml, or the minimum supported rust version increased...  

Perhaps the `.github/workflows/rust.yml` failure is a follow-on error because the other two checks failed?

**Comment by tarcieri** [comment]
>  I guess the dependency needs to be changed to an earlier version of toml, or the minimum supported rust version increased...

That's annoying. However, since the `cargo-audit` MSRV is already 1.36.0, we can go ahead and bump the MSRV for this crate to 1.36.0 as well.

> Perhaps the .github/workflows/rust.yml failure is a follow-on error because the other two checks failed?

The only time I've seen these are as an internal error inside Actions itself, however I think if you correct the MSRV-related errors it will still be mergeable even with that failing.

**Comment by tjodden** [comment]
Bumping MSRV to 1.36 seems to have fixed all 3 failures. :tada:

**Comment by tarcieri** [comment]
Thank you!

**Comment by jsgf** [comment]
Thanks!

**Comment by jsgf** [comment]
Any chance of a crates.io bump to include this?

**Comment by tarcieri** [comment]
Sure, I've been meaning to cut some new releases including the new `cargo audit --fix` feature

**Pull request merged**
