### PR TITLE
Fix parsing error on windows

### PR DESCRIPTION
**Pull request by Jake-Shadle**
Resolves: #294

### CODE REVIEW

**Comment by tarcieri** [comment]
Hrmm, odd that the tests are failing...

**Comment by Jake-Shadle** [comment]
Ahh, it's because the lockfile is pointing at rand_core 0.6.1 which has https://rustsec.org/advisories/RUSTSEC-2021-0023, so it was correct in reporting there was a vulnerability. :slightly_smiling_face:

**Comment by tarcieri** [comment]
@Jake-Shadle can you rebase now that #296 is landed?

**Comment by Jake-Shadle** [comment]
Yup, done.

**Pull request merged**
